# Generated by Django 4.0 on 2022-01-10 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('userid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('log_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OptionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('prog_id', models.CharField(max_length=50)),
                ('prog_name', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=50)),
                ('option_name', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('system_name', models.CharField(max_length=50)),
                ('prog_name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
