# Generated by Django 4.0.1 on 2022-03-09 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=True, verbose_name='有效值')),
                ('apps', models.CharField(max_length=50, verbose_name='应用类别')),
                ('name', models.CharField(max_length=50, verbose_name='配置名')),
                ('value', models.CharField(default='', max_length=500, verbose_name='配置值')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=50, verbose_name='创建人')),
                ('modidate', models.DateTimeField(default='', null=True, verbose_name='修改时间')),
                ('modiuser', models.CharField(default='', max_length=50, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '配置信息表',
                'verbose_name_plural': '配置信息表',
            },
        ),
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urls', models.CharField(default='', max_length=500, verbose_name='网址')),
                ('apps', models.CharField(max_length=50, verbose_name='应用类别')),
                ('model', models.CharField(max_length=50, verbose_name='模块名')),
                ('key', models.CharField(max_length=50, verbose_name='数据主键')),
                ('value', models.CharField(default='', max_length=255, verbose_name='数据值')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=50, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '日志记录表',
                'verbose_name_plural': '日志记录表',
            },
        ),
    ]
