# Generated by Django 4.0.1 on 2022-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='browser_type',
            field=models.CharField(default='', max_length=50, verbose_name='浏览器类型'),
        ),
        migrations.AddField(
            model_name='applog',
            name='device_type',
            field=models.CharField(default='', max_length=50, verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='applog',
            name='methods',
            field=models.CharField(default='get', max_length=50, verbose_name='访问方法'),
        ),
        migrations.AddField(
            model_name='applog',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='用户名称'),
        ),
        migrations.AddField(
            model_name='applog',
            name='req',
            field=models.CharField(default='', max_length=5000, verbose_name='传入数据'),
        ),
        migrations.AddField(
            model_name='applog',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='操作用户'),
        ),
        migrations.AlterField(
            model_name='applog',
            name='apps',
            field=models.CharField(default='', max_length=50, verbose_name='应用类别'),
        ),
        migrations.AlterField(
            model_name='applog',
            name='createuser',
            field=models.CharField(default='', max_length=50, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='applog',
            name='key',
            field=models.CharField(default='', max_length=50, verbose_name='数据主键'),
        ),
        migrations.AlterField(
            model_name='applog',
            name='model',
            field=models.CharField(default='', max_length=50, verbose_name='模块名'),
        ),
    ]
