# Generated by Django 4.0.1 on 2022-03-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dept_id',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_id',
            new_name='type',
        ),
    ]
