# Generated by Django 4.0.1 on 2022-03-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0006_user_self_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
