# Generated by Django 4.0.1 on 2022-04-06 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0009_permissionbase_parent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.BooleanField(default=0)),
                ('new', models.BooleanField(default=0)),
                ('edit', models.BooleanField(default=0)),
                ('delete', models.BooleanField(default=0)),
                ('print', models.BooleanField(default=0)),
                ('export', models.BooleanField(default=0)),
                ('lock', models.BooleanField(default=0)),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
                ('modidate', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modiuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
                ('perm_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='permission_base', to='appUsers.permissionbase')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type', to='appUsers.usertype')),
            ],
            options={
                'verbose_name': '用户类型权限表',
                'verbose_name_plural': '用户类型权限表',
            },
        ),
    ]
