# Generated by Django 4.0.1 on 2022-04-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0010_usertypepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertypepermission',
            old_name='perm_id',
            new_name='perm',
        ),
    ]
