# Generated by Django 4.0.1 on 2022-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0011_rename_perm_id_usertypepermission_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionbase',
            name='image',
            field=models.CharField(default='', max_length=100, verbose_name='图标'),
        ),
    ]
