# Generated by Django 4.0.1 on 2022-03-11 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0003_alter_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroupDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissionid', models.IntegerField(verbose_name='权限id')),
                ('permissionname', models.CharField(max_length=50, verbose_name='权限名')),
                ('run', models.BooleanField(default=0)),
                ('new', models.BooleanField(default=0)),
                ('edit', models.BooleanField(default=0)),
                ('delete', models.BooleanField(default=0)),
                ('print', models.BooleanField(default=0)),
                ('output', models.BooleanField(default=0)),
                ('lock', models.BooleanField(default=0)),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
                ('modidate', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modiuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '组权限表_表身',
                'verbose_name_plural': '组权限表_表身',
            },
        ),
        migrations.CreateModel(
            name='PermissionGroupTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=50, verbose_name='权限组名')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('createuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
                ('modidate', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('modiuser', models.CharField(max_length=50, null=True, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '组权限表_表头',
                'verbose_name_plural': '组权限表_表头',
            },
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AddField(
            model_name='user',
            name='client_no',
            field=models.CharField(default='', max_length=100, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='permissionbase',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='permissiongroupdetail',
            name='group_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_title', to='appUsers.permissiongrouptitle'),
        ),
    ]
