# Generated by Django 4.0.1 on 2022-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0004_permissiongroupdetail_permissiongrouptitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erp_no',
            field=models.CharField(default='', max_length=100, verbose_name='erp系统编号'),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_no',
            field=models.CharField(default='', max_length=100, verbose_name='hr工号'),
        ),
    ]
