# Generated by Django 4.0.1 on 2022-03-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBase', '0002_applog_browser_type_applog_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applog',
            name='user_type',
            field=models.CharField(default='', max_length=50, verbose_name='用户类型'),
        ),
    ]
